targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - lib/**.dart
    builders:
      freezed:
        enabled: false
      mockito|mockBuilder:
        enabled: true
        generate_for:
          include:
            - lib/src/service.dart
      riverpod_generator:
        enabled: false
