name: google_cloud_auth_service
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: https://github.com/nagakuta/flutter_modules/google_cloud_auth_service/
publish_to: https://dart.cloudsmith.io/nagakuta_flutter/modules/

environment:
  sdk: ^3.0.0

dependencies:
  # Freezed Annotation
  freezed_annotation: ^2.0.0

  # GoogleAPIs Auth
  googleapis_auth: ">=1.4.0 <1.5.0"

  # Http
  http: ^1.0.0

  # Meta
  meta: ^1.0.0

  # Mockito
  mockito: ^5.0.0

  # Riverpod
  riverpod: ^2.0.0

  # Riverpod Annotation
  riverpod_annotation: ^2.0.0

dev_dependencies:
  # Build Runner
  build_runner: ^2.0.0

  # Freezed
  freezed: ^2.0.0

  lints: ^2.0.0

  # Riverpod Generator
  riverpod_generator: ^2.0.0

  test: ^1.0.0
